package constants;

public enum InviteTypes {

    BOT,
    BOT_REMINDER,
    WEBSITE,
    WEBSITE_DISCORD_SERVERS_ME,
    WEBSITE_TOPGG,
    TOP_GG,
    BOTS_ONDISCORD_XYZ,
    DISCORD_BOTS_GG,
    DISCORDBOTLIST_COM,
    BOTSFORDISCORD_COM,
    DISCORD_BOATS,
    TOP_BOTS_XYZ,

}