package Constants;

public interface Permission {
    int     ATTACH_FILES_TO_TEXT_CHANNEL = 0x1,
            BAN_USER = 0x2,
            CHANGE_OWN_NICKNAME = 0x4,
            REMOVE_REACTIONS_OF_OTHERS_IN_TEXT_CHANNEL = 0x8,
            CREATE_CHANNELS_ON_SERVER = 0x10,
            MANAGE_EMOJIS_ON_SERVER = 0x20,
            DEAFEN_MEMBERS_ON_SERVER = 0x40,
            ADD_NEW_REACTIONS = 0x80,
            EMBED_LINKS_IN_TEXT_CHANNELS = 0x100,
            KICK_USER = 0x200,
            MANAGE_MASSAGES_IN_TEXT_CHANNEL  = 0x400,
            MANAGE_NICKNAMES_ON_SERVER = 0x800,
            MANAGE_ROLES_ON_SERVER = 0x1000,
            MANAGE_SERVER = 0x2000,
            MENTION_EVERYONE_IN_TEXT_CHANNEL = 0x4000,
            MOVE_MEMBERS_ON_SERVER = 0x8000,
            MUTE_MEMBERS = 0x10000,
            READ_MESSAGE_HISTORY_OF_TEXT_CHANNEL = 0x20000,
            WRITE_IN_TEXT_CHANNEL = 0x40000,
            VIEW_AUDIT_LOG_OF_SERVER = 0x80000,
            USE_TTS_IN_TEXT_CHANNEL = 0x100000,
            USE_EXTERNAL_EMOJIS_IN_TEXT_CHANNEL = 0x200000,
            SEE_CHANNEL = 0x400000,
            CONNECT = 0x800000,
            MANAGE_CHANNEL = 0x1000000,
            MANAGE_PERMISSIONS_IN_CHANNEL = 0x2000000;

    int MAX = MANAGE_PERMISSIONS_IN_CHANNEL;
}