package core.featurelogger;

public enum PremiumFeature {

    AI, CUSTOM_COMMANDS, ALERTS, REACTION_ROLES, ROLE_ASSIGNMENTS, TRIGGER_DELETE, REMINDERS, TICKETS, NEW_KICK_BAN,
    CLEAR, FISHERY, INVITE_TRACKING, PIXIV, BOORUS, COMMAND_CHANNEL_SHORTCUTS

}
