package core.featurelogger;

public enum PremiumFeature {

    AI, CUSTOM_COMMANDS_LIMIT, ALERTS_USER_MESSAGE, ALERTS_MIN_TRIGGER_INTERVAL, ALERTS_LIMIT,
    REACTION_ROLES_LIMIT, ROLE_ASSIGNMENTS, TRIGGER_DELETE, REMINDERS_REPEAT, TICKETS_AUTO_CLOSE, TICKETS_LOGS,
    TICKETS_TOPICS, NEW_KICK_BAN, CLEAR_OLD_MESSAGES, FISHERY_MANAGE, FISHERY_SPAWN, FISHERY_PROBABILITIES,
    FISHERY_VOICE_HOURS_LIMIT, INVITE_TRACKING_MANAGE, PIXIV, BOORUS_HIGHER_LIMIT, BOORUS_VIDEOS, BOORUS_LOAD_MORE_BUTTON,
    BOORUS_PREMIUM_ONLY, COMMAND_CHANNEL_SHORTCUTS, AUTO_ROLES_SYNC, BAN_APPEALS, CUSTOM_ROLE_PLAY

}
